In [3]:
import numpy as np
import matplotlib.pyplot as pyp
import pandas as pd

In [4]:
data = pd.read_csv('Data.csv')

In [5]:
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [6]:
x = data.iloc[:,:-1].values

In [7]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [8]:
y = data.iloc[:,-1].values

In [9]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [28]:
from sklearn.impute import SimpleImputer

In [29]:
si = SimpleImputer(missing_values = np.nan, strategy = 'mean') 

In [66]:
x[:, 1:] = si.fit_transform(x[:, 1:])

In [32]:
si.fit(x[:, 1:])

SimpleImputer()

In [33]:
x[:, 1:] = si.transform(x[:, 1:])

In [34]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [35]:
from sklearn.compose import ColumnTransformer

In [36]:
from sklearn.preprocessing import OneHotEncoder

In [42]:
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')

In [43]:
x = ct.fit_transform(x)

In [44]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [45]:
from sklearn.preprocessing import LabelEncoder

In [46]:
le = LabelEncoder()

In [47]:
y = le.fit_transform(y)

In [48]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [49]:
from sklearn.model_selection import train_test_split

In [53]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.4,random_state =1)

In [54]:
print(x_train)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [55]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]]


In [56]:
print(y_train)

[0 0 1 1 0 1]


In [57]:
print(y_test)

[0 1 0 1]


In [60]:
from sklearn.preprocessing import StandardScaler

In [61]:
sc = StandardScaler()

In [62]:
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])

In [63]:
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [64]:
print(x_train)

[[1.0 0.0 0.0 0.46236448688011816 0.42119409708279393]
 [0.0 0.0 1.0 -0.29423194619643933 -0.475541722512831]
 [0.0 0.0 1.0 -1.6813254068367947 -1.5353204183985696]
 [1.0 0.0 0.0 0.9667621089311564 0.9918441640981916]
 [0.0 1.0 0.0 1.2189609199566755 1.3179299166784189]
 [1.0 0.0 0.0 -0.672530162734718 -0.7201060369480015]]


In [65]:
print(x_test)

[[0.0 1.0 0.0 -1.303027190298516 -1.0461917895282287]
 [1.0 0.0 0.0 -0.4203313517091989 0.013586906357509865]
 [0.0 0.0 1.0 -0.1961546307976262 -1.2092346658183424]
 [0.0 1.0 0.0 -0.04203313517092016 -0.24909328322100627]]
