In [1]:
import numpy as np
import matplotlib.pyplot as ptp
import pandas as pd

In [2]:
data = pd.read_csv('Data.csv')

In [8]:
x = data.iloc[:, :-1].values

In [9]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [10]:
type(x)

numpy.ndarray

In [17]:
y= data.iloc[:, 3].values

In [18]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [19]:
from sklearn.impute import SimpleImputer

In [24]:
Imputer = SimpleImputer(missing_values =np.nan, strategy ='mean')


In [25]:
x[:,1:] = Imputer.fit_transform(x[:,1:])

In [26]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [42]:
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(),[0])], remainder ='passthrough')

In [47]:
x = ct.fit_transform(x)

In [48]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [53]:
from sklearn.preprocessing import LabelEncoder

In [55]:
le = LabelEncoder()

In [56]:
y = le.fit_transform(y)

In [57]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [59]:
from sklearn.model_selection import train_test_split

In [69]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.5, random_state =1)

In [70]:
print(x_train)

[[0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [71]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]]


In [72]:
print(y_train)

[0 1 1 0 1]


In [73]:
print(y_test)

[0 1 0 1 0]


In [75]:
from sklearn.preprocessing import StandardScaler

In [77]:
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])

In [78]:
print (x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [79]:
print(x_train)

[[0.0 0.0 1.0 -0.18824832213400483 -0.36371987181604676]
 [0.0 0.0 1.0 -1.482455536805287 -1.3487945246511734]
 [1.0 0.0 0.0 0.9883036912035243 1.0002296474941286]
 [0.0 1.0 0.0 1.2236140938710303 1.3033295406741676]
 [1.0 0.0 0.0 -0.5412139261352636 -0.591044791701076]]


In [80]:
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [81]:
print(x_test)

[[0.0 1.0 0.0 -1.1294899328040282 -0.894144684881115]
 [1.0 0.0 0.0 -0.3059035234677578 0.09092996795401169]
 [0.0 0.0 1.0 -0.09673872109664136 -1.0456946314711344]
 [0.0 1.0 0.0 0.047062080533501 -0.1532338348854639]
 [1.0 0.0 0.0 0.5176828858685126 0.4698048344290604]]
