In [118]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [119]:
pwd

'/home/prnc/PS_DS'

In [120]:
data = pd.read_csv('Data.csv')

In [121]:
x = data.iloc[:,:-1].values

In [122]:
y = data.iloc[:, -1].values

In [123]:
type(x)

numpy.ndarray

In [124]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [125]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [126]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')


In [127]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [128]:

imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

In [129]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [148]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [131]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder='passthrough')

In [132]:
x = ct.fit_transform(x)

In [133]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [134]:
type(x)

numpy.ndarray

In [135]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [136]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [137]:
type(x)

numpy.ndarray

In [138]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size =0.3, random_state=1)

In [139]:
print(x_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [140]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]


In [141]:
print(y_train)

[1 0 0 1 1 0 1]


In [142]:
print(y_test)

[0 1 0]


In [143]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [144]:
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])


In [145]:
x_test[:,3:]= sc.transform(x_test[:, 3:])

In [146]:
print(x_train)

[[0.0 1.0 0.0 -0.038910211282047996 -0.22960023388015188]
 [1.0 0.0 0.0 0.5058327466666259 0.49120534884662787]
 [0.0 0.0 1.0 -0.3112816902563849 -0.4731156334500103]
 [0.0 0.0 1.0 -1.809324824615238 -1.6127677034369463]
 [1.0 0.0 0.0 1.0505757046152997 1.1048641557626704]
 [0.0 1.0 0.0 1.3229471835896367 1.455526331143266]
 [1.0 0.0 0.0 -0.7198389087178904 -0.736112264985457]]


In [147]:
print(x_test)

[[0.0 1.0 0.0 -1.4007676061537326 -1.0867744403660526]
 [1.0 0.0 0.0 -0.4474674297435534 0.05287762962088326]
 [0.0 0.0 1.0 -0.20535944843303158 -1.2621055280563505]]
